apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yl-nginx-webapp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/nginx-webapp
    repoURL: https://github.com/slim-sandbox/argocd-demo.git
    targetRevision: HEAD
  destination:
    namespace: yl-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
